apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-sample-app-master
spec:
  selector:
    matchLabels:
      app: java-sample-app-master
  template:
    metadata:
      labels:
        app: java-sample-app-master
    spec:
      containers:
      - name: java-sample-app-master
        image: kulbhushanmayer/kaniko:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
